name: newsindie
description: "A newspaper-style news reader app with monochrome design"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management & DI
  get: ^4.6.6
  
  # Network
  dio: ^5.4.0
  
  # Local Database (CRUD)
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.0
  
  # UI
  google_fonts: ^6.1.0
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  timeago: ^3.6.1
  fl_chart: ^0.66.0
  
  # Utils
  share_plus: ^7.2.2
  url_launcher: ^6.2.5
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
